spring.application.name=recipeshare
server.port=8081
# Log levels
logging.level.root=INFO
logging.level.com.mcon152.recipeshare.web=DEBUG
logging.level.org.springframework.web=INFO
logging.patter.console=%d{HH:mm:ss.SSS} [%thread] %clr(%-5level) %logger{36} [recipe=%X{recipeTitle}] - %clr(%msg){magenta}%n

# Base log file
logging.file.name=logs/recipeshare.log

# Rolling policy configuration
logging.logback.rollingpolicy.file-name-pattern=logs/recipeshare-%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.clean-history-on-start=true